[project]
name = "py-droplets"
description = "Python package for describing and analyzing droplets in experiments and simulations"
authors = [
    {name = "David Zwicker", email="david.zwicker@ds.mpg.de"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9,<3.14"
dynamic = ["version"]

keywords = ["emulsions", "image-analysis"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

# Requirements for setuptools
dependencies = [
    "h5py>=2.10",
    "matplotlib>=3.1",
    "numba>=0.59",
    "numpy>=1.22",
    "scipy>=1.4",
    "py-pde>=0.43",
]

[project.urls]
homepage = "https://github.com/zwicker-group/py-droplets"
documentation = "http://py-droplets.readthedocs.io"
repository = "https://github.com/zwicker-group/py-droplets"

[build-system]
requires = [
    "setuptools>=61",
    "setuptools_scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true
zip-safe = false  # required for mypy to find the py.typed file

[tool.setuptools.packages.find]
include = ["droplets*"]
exclude = ["*.tests", "*.tests.*", "tests.*", "tests"]
namespaces = false

[tool.setuptools.exclude-package-data]
"*" = ["*.tests", "*.tests.*", "tests.*", "tests"]

[tool.setuptools_scm]
write_to = "droplets/_version.py"
[tool.ruff]
target-version = "py38"
exclude = ["scripts/templates"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
    "UP",  # pyupgrade
    "I",  # isort
    "A",  # flake8-builtins 
    "B",  # flake8-bugbear
    "F",  # pyflakes
    "C4",  # flake8-comprehensions
    "FA", # flake8-future-annotations
    "ISC", # flake8-implicit-str-concat
    "ICN", # flake8-import-conventions
    "LOG", # flake8-logging
    "G", # flake8-logging-format
    "PIE", # flake8-pie
    "PT", # flake8-pytest-style
    "Q", # flake8-quotes
    "RSE", # flake8-raise
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "PTH", # flake8-use-pathlib
]
ignore = ["B007", "B027", "B028", "F401", "F403", "SIM108", "ISC001", "PT006", "PT011", "RET504", "RET505", "RET506"]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "my-modules", "self", "local-folder"]

[tool.ruff.lint.isort.sections]
my-modules = ["pde"]
self = ["droplets"]

[tool.black]
target_version = ["py39"]

[tool.isort]
profile = "black"
src_paths = ["droplets", "examples", "scripts", "tests"]
known_first_party = "pde"
known_self = "droplets"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "SELF", "LOCALFOLDER"]

[tool.pytest.ini_options]
addopts = "--strict-markers"
filterwarnings = [
    'ignore:.*importing the ABCs from.*:DeprecationWarning',
    'ignore:.*IPython.utils.signatures backport for Python 2 is deprecated.*:DeprecationWarning',
    'ignore:.*scipy.sparse.*:DeprecationWarning',
]

[tool.coverage.report]
omit = ['*/test*']

[tool.mypy]
python_version = "3.9"
plugins = "numpy.typing.mypy_plugin"
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "numba.*"
ignore_missing_imports = true
ignore_errors = false
follow_imports = "skip"
follow_imports_for_stubs = true

[[tool.mypy.overrides]]
module = [
    "h5py.*",
    "IPython.*",
    "ipywidgets.*",
    "matplotlib.*",
    "mpl_toolkits.*",
    "mpi4py.*",
    "napari.*",
    "numba_mpi.*",
    "numpy.*",
    "pandas.*",
    "pyfftw.*",
    "pygmsh.*",
    "pytest.*",
    "qtpy.*",
    "scipy.*",
    "sympy.*",
    "tqdm.*",
]
ignore_missing_imports = true